// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/embedded/embeddedproto/gpio.proto

package embeddedproto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPIOConfigs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*GPIOConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *GPIOConfigs) Reset() {
	*x = GPIOConfigs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_embedded_embeddedproto_gpio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPIOConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPIOConfigs) ProtoMessage() {}

func (x *GPIOConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedded_embeddedproto_gpio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPIOConfigs.ProtoReflect.Descriptor instead.
func (*GPIOConfigs) Descriptor() ([]byte, []int) {
	return file_pkg_embedded_embeddedproto_gpio_proto_rawDescGZIP(), []int{0}
}

func (x *GPIOConfigs) GetConfigs() []*GPIOConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type GPIOConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Direction   int32  `protobuf:"varint,2,opt,name=Direction,proto3" json:"Direction,omitempty"`
	ActiveLevel int32  `protobuf:"varint,3,opt,name=ActiveLevel,proto3" json:"ActiveLevel,omitempty"`
	Value       bool   `protobuf:"varint,4,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *GPIOConfig) Reset() {
	*x = GPIOConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_embedded_embeddedproto_gpio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPIOConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPIOConfig) ProtoMessage() {}

func (x *GPIOConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedded_embeddedproto_gpio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPIOConfig.ProtoReflect.Descriptor instead.
func (*GPIOConfig) Descriptor() ([]byte, []int) {
	return file_pkg_embedded_embeddedproto_gpio_proto_rawDescGZIP(), []int{1}
}

func (x *GPIOConfig) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GPIOConfig) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *GPIOConfig) GetActiveLevel() int32 {
	if x != nil {
		return x.ActiveLevel
	}
	return 0
}

func (x *GPIOConfig) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_pkg_embedded_embeddedproto_gpio_proto protoreflect.FileDescriptor

var file_pkg_embedded_embeddedproto_gpio_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x2f, 0x65,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x70, 0x69,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65,
	0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0b, 0x47, 0x50, 0x49, 0x4f, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x50, 0x49, 0x4f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x72, 0x0a, 0x0a, 0x47, 0x50, 0x49, 0x4f, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x90, 0x01, 0x0a, 0x04,
	0x47, 0x50, 0x49, 0x4f, 0x12, 0x3f, 0x0a, 0x07, 0x47, 0x50, 0x49, 0x4f, 0x47, 0x65, 0x74, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x50, 0x49, 0x4f, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0d, 0x47, 0x50, 0x49, 0x4f, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x19, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65,
	0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x50, 0x49, 0x4f, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x19, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x50, 0x49, 0x4f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x00, 0x42, 0x39,
	0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x2d, 0x63, 0x6c, 0x61, 0x70, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x2f, 0x65, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_embedded_embeddedproto_gpio_proto_rawDescOnce sync.Once
	file_pkg_embedded_embeddedproto_gpio_proto_rawDescData = file_pkg_embedded_embeddedproto_gpio_proto_rawDesc
)

func file_pkg_embedded_embeddedproto_gpio_proto_rawDescGZIP() []byte {
	file_pkg_embedded_embeddedproto_gpio_proto_rawDescOnce.Do(func() {
		file_pkg_embedded_embeddedproto_gpio_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_embedded_embeddedproto_gpio_proto_rawDescData)
	})
	return file_pkg_embedded_embeddedproto_gpio_proto_rawDescData
}

var file_pkg_embedded_embeddedproto_gpio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_embedded_embeddedproto_gpio_proto_goTypes = []interface{}{
	(*GPIOConfigs)(nil), // 0: embeddedproto.GPIOConfigs
	(*GPIOConfig)(nil),  // 1: embeddedproto.GPIOConfig
	(*empty.Empty)(nil), // 2: google.protobuf.Empty
}
var file_pkg_embedded_embeddedproto_gpio_proto_depIdxs = []int32{
	1, // 0: embeddedproto.GPIOConfigs.configs:type_name -> embeddedproto.GPIOConfig
	2, // 1: embeddedproto.GPIO.GPIOGet:input_type -> google.protobuf.Empty
	1, // 2: embeddedproto.GPIO.GPIOConfigure:input_type -> embeddedproto.GPIOConfig
	0, // 3: embeddedproto.GPIO.GPIOGet:output_type -> embeddedproto.GPIOConfigs
	1, // 4: embeddedproto.GPIO.GPIOConfigure:output_type -> embeddedproto.GPIOConfig
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_embedded_embeddedproto_gpio_proto_init() }
func file_pkg_embedded_embeddedproto_gpio_proto_init() {
	if File_pkg_embedded_embeddedproto_gpio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_embedded_embeddedproto_gpio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPIOConfigs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_embedded_embeddedproto_gpio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPIOConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_embedded_embeddedproto_gpio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_embedded_embeddedproto_gpio_proto_goTypes,
		DependencyIndexes: file_pkg_embedded_embeddedproto_gpio_proto_depIdxs,
		MessageInfos:      file_pkg_embedded_embeddedproto_gpio_proto_msgTypes,
	}.Build()
	File_pkg_embedded_embeddedproto_gpio_proto = out.File
	file_pkg_embedded_embeddedproto_gpio_proto_rawDesc = nil
	file_pkg_embedded_embeddedproto_gpio_proto_goTypes = nil
	file_pkg_embedded_embeddedproto_gpio_proto_depIdxs = nil
}
