version: '3'

tasks:
  embedded:
    cmds:
      - go run ./cmd/embedded
  proto:
    cmds:
      - >
        protoc
        --go_out=.
        --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        pkg/embedded/embeddedproto/*.proto
  test:
    cmds:
      - go test ./...